### PR TITLE
 Implement Search and integration with api 

### PR DESCRIPTION
**Pull request by Nailashaheen**
Here is live link [LIVE](https://interviews-exercises-one.vercel.app/search)

### CODE REVIEW

**Review by hamxabaig — CHANGES_REQUESTED** [review]
Hi @Nailashaheen, few comments:

- We value design a lot at Space Next Door. Try to make sure its pixel perfect. I'll let u review yourself where it needs improvement.
- ~Make sure API is being called reasonably (Hint: Async search can be tricky)~
- After resolving these, comment the link to the new deployment.

Let me know when to re-review, you can request a review from me in the PR.

**Comment by hamxabaig** [comment]
@Nailashaheen you can leave the 2nd point from my comment. I think it got mixed up between different PRs. I've striked it out. Thanks

**Comment by Nailashaheen** [comment]
> @Nailashaheen you can leave the 2nd point from my comment. I think it got mixed up between different PRs. I've striked it out. Thanks
@hamxabaig I have updated the changes. Please have a look at it. Thanks

**Comment by Nailashaheen** [comment]
> @Nailashaheen you can leave the 2nd point from my comment. I think it got mixed up between different PRs. I've striked it out. Thanks

Okay sure.

**Pull request closed without merging**
